//index.ts for services
// Este archivo sirve como punto de entrada para exportar todos los servicios de la aplicación.
// Esto permite importar todos los servicios desde un solo lugar, facilitando su uso en otras partes de la aplicación.
export * from "./accion.service"
//export * from "./ciudad.service"
//export * from "./detalle-factura.service"
//export * from "./domicilio.service"
export * from "./estado.service"
//export * from "./factura.service"
export * from "./informe.service"
//export * from "./medio-de-pago.service"
export * from "./modalidad.service"
export * from "./modulo.service"
export * from "./obra-social.service"
export * from "./paciente-tiene-informe.service"
//export * from "./paciente-tiene-sesion.service"
export * from "./paciente.service"
//export * from "./pais.service"
export * from "./perfil-tiene-permiso.service"
export * from "./perfil.service"
export * from "./permiso.service"
//export * from "./persona-tiene-factura.service"
export * from "./persona.service"
export * from "./psicologo.service"
export * from "./sesion.service"
//export * from "./telefono.service"
//export * from "./tipo-factura.service"
export * from "./usuario-tiene-perfil.service"
export * from "./usuario.service"