// index.ts for entities
// Este archivo sirve como punto de entrada para exportar todas las entidades de la aplicación.
// Esto permite importar todas las entidades desde un solo lugar, facilitando su uso en otras partes de la aplicación.
// También se puede utilizar para inicializar la conexión a la base de datos y cargar las entidades necesarias.
export * from "./base-entity"
export * from "./accion.entity"
export * from "./ciudad.entity"
export * from "./detalle-factura.entity"
export * from "./domicilio.entity"
export * from "./estado.entity"
export * from "./factura.entity"
export * from "./informe.entity"
export * from "./medio-de-pago.entity"
export * from "./modalidad.entity"
export * from "./modulo.entity"
export * from "./obra-social.entity"
export * from "./paciente-tiene-informe.entity"
export * from "./paciente-tiene-sesion.entity"
export * from "./paciente.entity"
export * from "./pais.entity"
export * from "./perfil-tiene-permiso.entity"
export * from "./perfil.entity"
export * from "./permiso.entity"
export * from "./persona-tiene-factura.entity"
export * from "./persona.entity"
export * from "./psicologo.entity"
export * from "./sesion.entity"
export * from "./telefono.entity"
export * from "./tipo-factura.entity"
export * from "./usuario-tiene-perfil.entity"
export * from "./usuario.entity"