import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Tu CSS global
import NextAuthProvider from "@/app/components/NextAuthProvider"; // El wrapper que crearemos abajo
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MemoPsy", 
  description: "Gestión de consultorio psicológico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Envuelve todo con el Provider de NextAuth */}
        <NextAuthProvider>
          {children}
          <Toaster 
            position="top-center" 
            toastOptions={{
              className: 'font-geist-sans',
              duration: 5000,
              //style: {
              //  background: "#447A7B",
              //  color: "#161617",
              //},
            }}
          /> 
        </NextAuthProvider>
      </body>
    </html>
  );
}

/*
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
  
// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Tu CSS global
import NextAuthProvider from "@/app/components/NextAuthProvider"; // El wrapper que crearemos abajo

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mi App de Psicología", // Cambia el título
  description: "Gestión de pacientes y sesiones", // Cambia la descripción
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es"> }
      <body className={inter.className}>
        }
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
*/