//index.ts for repositories
// Este archivo sirve como punto de entrada para exportar todos los repositorios de la aplicación.
// Esto permite importar todos los repositorios desde un solo lugar, facilitando su uso en otras partes de la aplicación.
export * from "./accion.repository"
//export * from "./ciudad.repository"
//export * from "./detalle-factura.repository"
//export * from "./domicilio.repository"
export * from "./estado.repository"
//export * from "./factura.repository"
export * from "./informe.repository"
//export * from "./medio-de-pago.repository"
export * from "./modalidad.repository"
export * from "./modulo.repository"
export * from "./obra-social.repository"
export * from "./paciente-tiene-informe.repository"
//export * from "./paciente-tiene-sesion.repository"
export * from "./paciente.repository"
//export * from "./pais.repository"
export * from "./perfil-tiene-permiso.repository"
export * from "./perfil.repository"
export * from "./permiso.repository"
//export * from "./persona-tiene-factura.repository"
export * from "./persona.repository"
export * from "./psicologo.repository"
export * from "./sesion.repository"
//export * from "./telefono.repository"
//export * from "./tipo-factura.repository"
export * from "./usuario-tiene-perfil.repository"
export * from "./usuario.repository"