//index.ts for models
// Este archivo sirve como punto de entrada para exportar todos los modelos de la aplicación.
// Esto permite importar todos los modelos desde un solo lugar, facilitando su uso en otras partes de la aplicación.
export * from "./base-model"
export * from "./accion.model"
export * from "./ciudad.model"
export * from "./detalle-factura.model"
export * from "./domicilio.model"
export * from "./estado.model"
export * from "./factura.model"
export * from "./informe.model"
export * from "./medio-de-pago.model"
export * from "./modalidad.model"
export * from "./modulo.model"
export * from "./obra-social.model"
export * from "./paciente-tiene-informe.model"
export * from "./paciente-tiene-sesion.model"
export * from "./paciente.model"
export * from "./pais.model"
export * from "./perfil-tiene-permiso.model"
export * from "./perfil.model"
export * from "./permiso.model"
export * from "./persona-tiene-factura.model"
export * from "./persona.model"
export * from "./psicologo.model"
export * from "./sesion.model"
export * from "./telefono.model"
export * from "./tipo-factura.model"
export * from "./usuario-tiene-perfil.model"
export * from "./usuario.model"